version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  web:
    build: .
    container_name: mlx-web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis-data: